%% Assess correlations between symptom scores and covariates

%% Initialization
% Define symptom severity scores (default symptom scores)
Y1 = [nanmean(insomnia_score(:,timePoints),2)];
Y2 = nanmean(phq2(:, timePoints),2);
Y3 = nanmean(n12_nervous(:, timePoints),2);
YY = [Y1 Y2 Y3];

%% Compute correlations of symptom scores and covariates

% bmi = info_table.f_21001_2_0;

[r,p] = corr(YY, ...
    [age ...
    gender == 'Female' ...
    townsend ...
    education_years ...
    CTS ...
    ATS ...
    smoking ...
    diabetes ...
    hypertension ...
    alcohol ...
    bmi ...
    medication], ...
    'rows', 'pairwise', ...
    'type', 'spearman');

% Correct for multiple comparisons
[~, ~, pa] = fdr(p(:));
pa = reshape(pa, size(p));

%% Report correlations:
R = cell(size(r,1), size(r,2));
for i = 1:numel(r)
    R{i} = sprintf('%.2f (p=%.3f)', r(i), p(i));
end
disp(R);

%% Present correlations in figure

figure('color', 'white');
hold on;

imagesc(r);

% Get indices where p-values are less than 0.05
[rows, cols] = find(pa < 0.05);

% Overlay stars on these indices
plot(cols, rows, 'p', ...
    'MarkerSize', 10, ...
    'MarkerEdgeColor', 'w', ...
    'MarkerFaceColor', 'w');

% Style figure
cm = flipud(cbrewer('div', 'RdBu', 1000));
cm(1,:) = [1 1 1];
caxis([-.3 .3]);
colormap(cm);
xticks(1:15);
yticks(1:3);

yticklabels({'Insomnia symptoms', ...
    'Depression symptoms', ...
    'Anxiety symptoms'});

xticklabels({'Age', ...
    'Gender', ...
    'SES', ...
    'Educational attainment', ...
    'Childhood stress', ...
    'Adulthood stress', ...
    'Smoking', ...
    'Diabetes', ...
    'Hypertension', ...
    'Alcohol use', ...
    'BMI', ...
    'Medication - Anxiolytics', ...
    'Medication - Antidepressants', ...
    'Medication - Antipsychotics', ...
    'Medication - Mood stabiliser'});

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Box', 'off', ...
    'LineWidth', 1);

colorbar

axis equal
axis tight

